`#todo` fix
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/BAM/AlignmentRelation.scala:102:16: not found: value spark_bam
[error]         import spark_bam._, hammerlab.path._
[error]                ^
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/BAM/AlignmentRelation.scala:102:29: not found: value hammerlab
[error]         import spark_bam._, hammerlab.path._
[error]                             ^
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/BAM/AlignmentRelation.scala:103:23: not found: value Path
[error]         val bamPath = Path(resolvedPath)
[error]                       ^
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/BAM/AlignmentRelation.scala:106:12: value loadReads is not a member of org.apache.spark.SparkContext
[error] possible cause: maybe a semicolon is missing before `value loadReads'?
[error]           .loadReads(bamPath)
[error]            ^
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/VCF/VCFRelation.scala:3:11: object projectglow is not a member of package io
[error] import io.projectglow.Glow
[error]           ^
[error] /development/projects/05_ds/spark/bdg-sequila/src/main/scala/org/biodatageeks/sequila/datasources/VCF/VCFRelation.scala:35:7: not found: value Glow
[error]       Glow.transform(m.toLowerCase(), inputDf, Map("reference_genome_path" -> ref_genome_path.get))
[error]       ^
[error] 6 errors found

See fix for `AliasViewChild` as per https://github.com/apache/spark/pull/22713